version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - calcnetwork

  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - calc_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - calcnetwork

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
        - STORAGE_TYPE=mysql
        - MYSQL_HOST=zipkin-storage
        - MYSQL_USER=zipkin
        - MYSQL_PASS=zipkin
        - MYSQL_DB=zipkin
    depends_on: 
      - zipkin-storage
    networks:
      - calcnetwork
    
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    volumes:
      - zipkin_data:/mysql/data
    networks:
      - calcnetwork
        
  addition-service:
    build:
      context: .
      dockerfile: AdditionService/Dockerfile
    deploy:
      replicas: 3
    networks:
      - calcnetwork

  calculation-history-api:
    build:
      context: .
      dockerfile: CalculationHistoryApi/Dockerfile
    networks:
      - calcnetwork

  subtraction-service:
    build:
      context: .
      dockerfile: SubtractionService/Dockerfile
    deploy:
      replicas: 3
    networks:
      - calcnetwork

  calculation-api:
    build:
      context: .
      dockerfile: CalculationApi/Dockerfile
    networks:
      - calcnetwork

volumes:
  calc_seq_data:
  zipkin_data:

networks:
  calcnetwork:
    driver: bridge